---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Register the output of the 'uptime' command
      command: uptime
      register: system_uptime

    - name: Print the output of the 'uptime' command
      debug:
        var: system_uptime.stdout

    - name: Print a message if the system resulted in a change.
      debug:
        msg: "Command resulted in a change"
      when: system_uptime is changed