---
- name: Install Apache Ubuntu
  hosts: apache
  become: true

  pre_tasks:
    - name: Update apt cache if needed.
      apt:
        update_cache: true
        cache_valid_time: 3600

  handlers:
    - import_tasks: ../handlers/apache.yml

  tasks:
    - import_tasks: ../tasks/apache.yml
      # vars:
      #   apache_package: test



    # - include_tasks: ../tasks/log.yml
    # - name: check for existing log files in dynamic log_files_path variable
    #   find:
    #     paths: "{{ item }}"
    #     patterns: "*.log"
    #   register: found_log_file_paths
    #   with_items: "{{ log_files_path }}"

- import_playbook: ./date.yml
