---
- name: Ensure Apache is installed
  apt:
    name: apache2
    state: present

- name: Copy test config file
  copy:
    src: ../files/test.conf
    dest: /etc/apache2/sites-available/test.conf
  notify: restart apache

- name: Make sure handlers are flushed inmediately
  meta: flush_handlers

- name: Ensure Apache is running and enabled
  service:
    name: apache2
    state: started
    enabled: yes