---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    # Syntax check will pass wether or not this file exists.
    - include_tasks: dates.yml

    # This will cause a failure, since it can be checked statically.
    # - import_tasks: free.yml

    - name: Print a debug message
      debug:
        msg: "This is a debug message"