---
- name: Install Apache.
  hosts: all
  become: true

  vars:
    apache_package: apache2
    apache_service: apache2

  handlers:
    - name: restart apache
      service:
        name: "{{ apache_service }}"
        state: restarted

  pre_tasks:
    - name: Override Apache vars for Red Hat
      set_fact:
        apache_package: httpd
        apache_service: httpd
      when: ansible_os_family == "RedHat"

  tasks:
    - name: Ensure Apache is installed
      package:
        name: "{{ apache_package }}"
        state: present

    - name: Copy a web page to the web server
      copy:
        content: |
          <html>
            <head>
              <title>Test Page</title>
            </head>
            <body>
              <h1>Test Page</h1>
              <p>This is a test page.</p>
            </body>
          </html>
        dest: /var/www/html/index.html
      notify: restart apache

    - name: Ensure Apache is running and starts at boot.
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true