---
name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Molecule Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos8
          - debian10

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule docker yamllint ansible-lint
        working-directory: ./episode8/01-molecule-playbook

      - name: Run Molecule tests
        run: |
          molecule test --all
        working-directory: ./episode8/01-molecule-playbook
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
